### ISSUE TITLE
FeedBack

### ISSUE THREAD

**Issue by ttexan1** [geek-line/code-database#10]
## 全体的
- [x] Goプロジェクトの基本をしっかりしよう
  - version1.13以降は go.modでパッケージの管理をすること
  - プロジェクト内のimportは相対パスではなく、go.modのmoduleに記されたpathをprefixとして使用すること
  - 参考：https://golang.org/doc/code.html#Command
- [ ] errを受け取ったら必ずエラーハンドリングをすること。
- [ ] os.Getenvみたいな外部リソースとの通信は重たいんだけど、configが呼ばれるたびにそれが呼び出されちゃってるから、configの内容はserver.goとかで初期化して変数で持っておいて、それを必要なところに渡す形の方が良い。

## Route, ハンドラー関係
- [x] routes情報はconfigurationなのでまとめるならconfigディレクトリの方が良いかも。(諸説あり)
- [ ] middlewareはhandlerの中でweb.goみたいなファイルを作ってメソッドを用意すれば十分だと思う、パッケージ分けるほどの量もないし。もし分けるとしても、webとかadaptersみたいなディレクトを切って、`web/handlers/*.go`, `web/middlewares/*.go`みたいなディレクトリ構成の方が意味的なまとまりがはっきりしやすい。ついでに、ページネーション関係の処理とかテンプレート関係の処理で似たようなのをいろんなところで何回も書いちゃってるから、それもまとめられるところはメソッドにすると良い。
- [ ] ルーティングがわかりにくい。意図がないのであれば、基本的にRestfulな設計が良い。
  - 参考：https://qiita.com/mserizawa/items/b833e407d89abd21ee72
- [ ] handlersの中身1アクションごとに、ファイルを分けているのはかなり見にくい。例えばloginとlogoutはセットだから、一つまとめて良いと思うし、リソースのCRUDはルーディングのまとまりごとにファイル分割するとかの方が見やすいと思う。
- [ ] 上の二つとも関係するけど、一つのhandlerの中でHTTPメソッドごとに条件分岐するのは、あまり綺麗な設計とは言えないかも。GetとPostってやることだいぶ違うし。
- [ ] structsパッケージっていうパッケージ名はあまりよくないかも。サービスの核となる知識な訳だからdomainとかの方が良い。またcomponentとentityを同じパッケージにまとめるのは意味的によくわからなくなってしまう。component.goの内容は基本的にpageに対応するものだから、handlerごとに個別で定義するので十分かと。確かに、個別で定義すると内容的に重複する定義が発生するかもだけど意味的な重複はないし多分まとめなくても大丈夫。
- [x] modelsディレクトリのファイル名のsuffixで_modelsにしてるのはDRYじゃない。

## データベース関連
- [ ] データベースのmigrationはどうやってするの？(migrationファイルを用意した方が良い。)
- [ ] データベースのpk, fk, not nullなどの制約をもし考えてないなら考えた方が良い。
- [ ] database/sqlパッケージはそんなに機能がなくて実装がバラバラしちゃうから、もしかしたらgormとかsqlboilerみたいなORMを使った方が良いかも。
- [ ] sql.Openを全てのリクエストに対して行っているけど、基本的にはそれはmainパッケージで行って、openしたdbを使い回せば良い(毎回openしてるとオーバーヘッドのコストが高い)

## その他
- [ ] switch文の書き方間違っている(動くけど)
https://github.com/geek-line/code-database/blob/037a89320fd4069788a350f62a08fb9648bad937/handlers/user_knowledges.go#L32
- [x] entityの種類によってCreatedAt, UpdatedAtがtime.Time型と、string型とあるけど分けてる意図はあるの?

**Comment by reibomaru** [comment]
> entityの種類によってCreatedAt, UpdatedAtがtime.Time型と、string型とあるけど分けてる意図はあるの?

mysqlのdatatime型をtime.Time型にscanできなかったため、string型が正しいです。string型に直しておきました。

**Comment by ttexan1** [comment]
`db, err := sql.Open("mysql", "root:@/?parseTime=true")`
でtime.Timeにparseできるよ。
https://stackoverflow.com/questions/29341590/how-to-parse-time-from-database

string型だとメモリ使用量が大きくなっちゃうし、適切な型を用いた方が後々の処理も楽だからtime.Timeに統一した方が良いと思うよ。

**Comment by reibomaru** [comment]
知りませんでした&ありがとうございます！そっちの方が良さげですね、直します！
